### ISSUE TITLE
Join the org

### ISSUE THREAD

**Issue by VasudevJaiswal** [AbhijithGanesh/AbhijithGanesh#1]
[Click Here For join the org](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)
Thank you

**Comment by AbhijithGanesh** [comment]
Comments: This issue is not pertinent to the repository

I shall see and know more about the JDCommunity soon.

**Comment by VasudevJaiswal** [comment]
> [Click Here For join the org](https://github.com/Jaidevstudio/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.yml&title=Please+invite+me+to+the+GitHub+Community+Organization)
> Thank you

Plz Check it again
